const EndPoints = {
  baseUrl: 'http://3.220.96.137:3000/api/',
  login: 'login',
  register: 'register',
  forgetPassword: 'forgetPassword',
  myAccountDetails: 'myAccountDetails',
  resetPassword: 'resetPassword',
  editUserProfile: 'editUserProfile',
  toRoomStatus: 'toRoomStatus',
  viewRoomDetails: 'viewRoomDetails',
  editRoom: 'editRoom',
  myRoomList: 'myRoomList',
  deleteRoom: 'deleteRoom',
  getNotification: 'getNotification',
  updateUserNotificationDetails: 'updateUserNotificationDetails',
  getUserNotification: 'getUserNotification',
  sendEmailOtp: 'sendEmailOtp',
  verifyEmailotp: 'verifyEmailotp',
  updatePassword: 'updatePassword',
  verfyOtp: 'verfyOtp',
};
export default EndPoints;
