const Labels = {
  Details: 'Details',
  ListingAgent: 'Listing Agent',
  Specification: 'Specification',
  Availablefor: 'Available For',
  ParkingAvailability: 'Parking Availability',
  WhichFloor: 'Which Floor',
  Dependency: 'Dependency',
  Furnished: 'Furnished',
  Description: 'Description',
  Search: 'Search',
  LocationInfo: 'Room Location information',
  fullAddress: 'Full Address',
  Distance: 'Distance',
  Time: 'Time To Reach Room',
  FILTER: 'FILTER',
  RESET: 'RESET',
  ALL: 'ALL',
  Notification: 'Notification',
  RoomLocation: 'Room Location',
  AppSettings: 'App Settings',
  Favourite: 'Favourite',
  MyPost: 'My Post',
  Chat: 'Chat',
  Upload: 'Upload',
  Map: 'Map',
  Profile: 'Profile',
  AllRooms: 'All Rooms  ',
  defaultLocation: 'Default Location',
  Review: 'Review',
};
export default Labels;
