/* eslint-disable no-undef */
export default Screen = {
  Home: 'Home',
  Login: 'Login',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  TabComponent: 'TabComponent',
  Upload: 'Upload',
  AllRooms: 'AllRooms',
  Fav: 'Fav',
  MyAccount: 'MyAccount',
  ActiveRoomTab: 'ActiveRoomTab',
  DeactiveRoomTab: 'DeactiveRoomTab',
  AllRoomTab: 'AllRoomTab',
  RenderRoom: 'RenderRoom',
  MyPost: 'MyPost',
  Settings: 'Settings',
  EditProfile: 'EditProfile',
  changePassword: 'changePassword',
  ContactUs: 'ContactUs',
  Logout: 'Logout',
  Search: 'Search',
  Splash: 'Splash',
  EmailVerify: 'EmailVerify',
  UploadFormSTP2: 'UploadFormSTP2',
  UploadNavigator: 'UploadNavigator',
  DetailsScreen: 'DetailsScreen',
};
